#!/bin/bash

NAME=recordthepiano
RUNDIR=/var/lib/recordthepiano

DESC=$NAME
APP=/usr/local/bin/recordthepiano
USER=recordthepiano
GROUP=recordthepiano
PIDFILE=/var/run/recordthepiano.pid
LOGFILE=/var/log/recordthepiano/recordthepiano.log

ulimit -n 65536

case "$1" in 
    start)
        echo -n "Starting $DESC... "
        # check for pid file
        if [ -f $PIDFILE ]; then
            echo "failed: already running."
            exit 1
        fi
	if ! start-stop-daemon -q --start --verbose --oknodo --chuid $USER:$GROUP --pidfile $PIDFILE --make-pidfile --background \
                                  --chdir $RUNDIR --exec /bin/bash -- -c "exec $APP > $LOGFILE 2>&1"
        then
            echo "failed."
            exit 1
        else
            exit 0
        fi
        ;;
    stop)
        echo -n "Stopping $DESC... "
        # check for pid file
        if [ ! -f $PIDFILE ]; then
            echo "not running."
            exit 0
        fi
        # attempt to terminate process
        if ! kill `cat $PIDFILE` ; then
            rm -f $PIDFILE
            echo "not running."
            exit 0
        fi
        # kill pid file
        rm -f $PIDFILE
        echo "success."
        exit 0
        ;;
    *)  
        echo "Usage: /etc/init.d/$NAME {start|stop}" >&2
        exit 1
        ;;
esac        

exit 0 
